language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install pandoc -y

# command to install dependencies
install:
  - pip install pipenv==2018.10.13
  - pipenv run make install-dev

# command to run tests
script:
  - pipenv run make lint
  - pipenv run make test

deploy:
  provider: pypi
  user: jsaon
  password:
    secure: ""
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
    python: 3.6