language: python

cache: pip

python:
- '3.6'
- 'nightly'

matrix:
  allow_failures:
  - python: 'nightly'

install:
- make install

script:
- make lint
- make test

deploy:
  provider: pypi
  user: jsaon
  password:
    secure: ""
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
    python:
      - 3.6
