jobs:
  build-and-test:
    docker:
      - image: python:3.6
    working_directory: /tmp/app
    environment:
      TZ: /usr/share/zoneinfo/Asia/Taipei
      # https://docs.pipenv.org/advanced.html#custom-virtual-environment-location
      WORKON_HOME: /tmp/venv
    steps:
      - checkout
      - restore_cache:
          keys:
            - talos-cache-181026-{{ checksum "Pipfile.lock" }}
            - talos-cache-181026
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Install dependencies
          command: |
            pipenv run pip install pip==18.0
            pipenv install --dev
      - save_cache:
          key:  talos-cache-181026-{{ checksum "Pipfile.lock" }}
          paths:
            - /tmp/venv
      - run:
          name: Flake8
          command: pipenv run python -m flake8 .
      - run:
          name: Test
          command: pipenv run make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
